### ISSUE TITLE
how to transparent update from monero v7 to v8 (cpu&gpu)

### ISSUE THREAD

**Issue by Quake4** [jceminer/cn_cpu_miner#21]
how i can it do?

now i choose 15 variation, but i get wrong share on current monero v7

![image](https://user-images.githubusercontent.com/29517243/46998667-e7f21100-d12b-11e8-9053-fe6c7ef6fed1.png)

**Comment by jceminer** [comment]
No autoswitch on JCE yet, so you have to stop it after the fork and restart it
for v7, param is --variation 3
for v8 --variation 15

Note the GPU version has been rushed because of lack of time and decent dev environment and provide bad performances. Sadly I didn't have time, and won't have any to fix it until november. The CPU part is mature and optimized.
