### ISSUE TITLE
Pool-managed Autoswitch and mining V8 only

### ISSUE THREAD

**Issue by Axadiw** [jceminer/cn_cpu_miner#26]
Hi,

is it possible somehow to specify which algorithms should be selected when using "Pool-managed Autoswitch" variany in JCE?

I have been previously mining on MoneroOcean with MM.js proxy miner, that've configured with manually gathered performance benchmarks, for example:

```
...
"algo_perf": {
     "cn/xtl": 54.17,
     "cn/2": 54.56,
     "cn/msr": 111.15,
     "cn-lite": 172.73,
     "cn-heavy": 29.44,
     "cn-heavy/tube": 22.53
    },
```

With these, MoneroOcean is able to decide which coin would be most profitable to mine on my setup (in my case, it would be cn-lite algorithm, a.k.a `Cryptolight V7 fork of April-2018`)

Unfortunately when I've configured JCE miner with variant 16 (Pool-managed Autoswitch) - it's mining only with `Cryptonight V8 fork of Oct-2018`.

Is it possible to specify somehow particular algorithms performance, that would be than used by MoneroOcean to decide which coin is most profitable to mine?

**Comment by jceminer** [comment]
Hi,

I advise to use the native Pool-managed Autoswitch feature now it's available, rather than an external tool.
You can speciafy what algorithm you mine with *manual config*.
Let's take an example, the config for a 4-core CPU, as in the doc:
 ```
/* This is the configuration when Cryptolight class algo is mined */
"cryptolight_cpu_threads_conf" : 
[ 
      { "cpu_architecture" : "auto", "affine_to_cpu" : 0, "use_cache" : true, "multi_hash":1 },
      { "cpu_architecture" : "auto", "affine_to_cpu" : 1, "use_cache" : true, "multi_hash":1 },
      { "cpu_architecture" : "auto", "affine_to_cpu" : 2, "use_cache" : true, "multi_hash":1 },
      { "cpu_architecture" : "auto", "affine_to_cpu" : 3, "use_cache" : true, "multi_hash":1 },
],
 
/* This is the configuration when Cryptonight class algo is mined */
"cryptonight_cpu_threads_conf" : 
[ 
      { "cpu_architecture" : "auto", "affine_to_cpu" : 0, "use_cache" : true, "multi_hash":1 },
      { "cpu_architecture" : "auto", "affine_to_cpu" : 2, "use_cache" : true, "multi_hash":1 },
],

/* This is the configuration when CN-Heavy class algo is mined */
"cn_heavy_cpu_threads_conf" : 
[ 
      { "cpu_architecture" : "auto", "affine_to_cpu" : 0, "use_cache" : true, "multi_hash":1 },
],
```
Configure one, two or three of these arrays according to your CPUs, and *remove* the ones you don't want.
Want no CN-Heavy class (no Heavy, Haven, Tube...)? remove "cn_heavy_cpu_threads_conf" array.
Want no CN-Light class (Turtlecoin...)? remove "cryptolight_cpu_threads_conf" array.

Technically you could remove the CN-class array, but I know MoneroOcean would refuse it.
Also it's very possible that MoneroOcean keeps mining CN-v8 for a whole day. During my tests, it saw it switch to Stellite twice, and never on any other algo.

**Comment by Axadiw** [comment]
exactly, I want to get rid of any external software (like MM.js) - I'm just comparing my current solution, where algo swithcing actually works.

Indeed, when I've turned on JCEMiner with autoswitch feature, it has been mining CN-v8 for neraly all day (with short exceptions for stellite and msr as well).

As I've said - for my setup, cryptolite is most profitable (I'm making a lot of profit from multihash=6 that's not available on other miners), and I can't use it on MoneroOcean :(

I know that we can't just point JCE miner with variant 4 (cryptolite), because MO would reject it (all miners that are connecting to MO should advertise themselves that they "support" at least CN-v8, which isn't true if you force variant on JCE).

Would it be possible to send `algo_perf` somehow to MO, like it's done with other tools used there (https://github.com/MoneroOcean/meta-miner / https://github.com/MoneroOcean/xmr-node-proxy)

**Comment by Axadiw** [comment]
Plus I have my JCE miner configurex exactly as you've presented: with 3 separate config blocks with `cryptolight_cpu_threads_conf`, `cryptonight_cpu_threads_conf` and `cn_heavy_cpu_threads_conf` sections

**Comment by Axadiw** [comment]
Great, thanks!

**Comment by jceminer** [comment]
Sorry i didn't had time to add it, i switched to the fixes for GPU version instead. My priorities change often... But i haven't give up, in fact it's quite a simple feature to add, compared to the GPU implementations...
Still planned for the next CPU version (so: 33g)

**Comment by Axadiw** [comment]
No worries @jceminer  - I'm looking forward for version 33g  than ! :)

**Comment by jceminer** [comment]
i'm done adding the feature, but during my tests, despite sending the new data "algo_perf" MoneroOcean still makes me mine v8, even when i set a very high algo_perf on other coins like XTL.
Is it due to the recent change on coins values, or it works with meta-miner and just my code is bad?
I ask you because you obviously have more experience on MO.

**Comment by jceminer** [comment]
It's online, the 0.33g Windows (linux version comes next)

**Comment by jceminer** [comment]
ho, no problem i start the linux build right now, easy. Should be online in a few hours, just to take time to test a bit.

**Comment by eLvErDe** [comment]
If its ready before midnight, I ll provide debs

**Comment by Axadiw** [comment]
So far it looks like this feature works without any problems. Thanks @jceminer again !:)
