### ISSUE TITLE
Invalid json in api

### ISSUE THREAD

**Issue by Quake4** [jceminer/cn_cpu_miner#9]
![image](https://user-images.githubusercontent.com/29517243/41774855-1a0653d4-762a-11e8-82fb-0fd3c5cdeccd.png)

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/41774959-847b8720-762a-11e8-9ab4-b973b8aeb0fb.png)

**Comment by jceminer** [comment]
You're right, that's a regression on 0.29d that has also been reported on Bitcointalk. That's what happens when you test too fast, my bad....
Version 0.29e is building right now, and will also fix a bug on 32+ cpu systems.

**Comment by Quake4** [comment]
thanks

**Comment by jceminer** [comment]
Fixed, but since the max is updated from time to time (when the log is updated) you may see from JSON the total higher than the max at the beginning of the mine session, while the hashrate stabilize, which looks rather strange.
I'll change that in next version, but won't do a new release for such a small glitch.
